spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: database
    password: database

cryptography:
  encryption:
    key: ${ENCRYPTION_KEY}
    algorithm: AES-GCM
  pseudonymize:
    active: true
  dsgvo-encryption:
    active: true